-- Based on the implemented API structure, here is the schema for Bike Fleet Management

-- 1. Main Bikes Table
CREATE TABLE IF NOT EXISTS bikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Basic Details
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- e.g., 'Scooter', 'Geared', 'Superbike'
    availability TEXT DEFAULT 'Available', -- 'Available', 'Booked', 'Maintenance', 'Limited', 'Coming Soon'
    status TEXT DEFAULT 'Active', -- Logical delete flag if needed
    
    -- Specs
    cc TEXT, -- e.g., '110cc', '350cc'
    transmission TEXT, -- 'Automatic', 'Manual'
    
    -- Pricing (Integers or Decimals)
    price_hour NUMERIC DEFAULT 0,
    price_day NUMERIC DEFAULT 0,
    price_week NUMERIC DEFAULT 0,
    price_month NUMERIC DEFAULT 0,
    price_quarterly NUMERIC DEFAULT 0,
    price_yearly NUMERIC DEFAULT 0,
    
    -- Deposit
    deposit NUMERIC DEFAULT 0,
    
    -- Booking Limits
    min_booking_hour NUMERIC DEFAULT 0,
    min_booking_day NUMERIC DEFAULT 0,
    
    -- Kilometer Limits
    km_limit_hour NUMERIC DEFAULT 0,
    km_limit_day NUMERIC DEFAULT 0,
    km_limit_week NUMERIC DEFAULT 0,
    km_limit_month NUMERIC DEFAULT 0,
    
    -- Extra Charges
    excess_km_charge NUMERIC DEFAULT 0
);

-- 2. Bike Images Table (One bike can have multiple images)
CREATE TABLE IF NOT EXISTS bike_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    bike_id BIGINT REFERENCES bikes(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0
);

-- 3. Bike Color Variants (Optional, if you use this feature)
CREATE TABLE IF NOT EXISTS bike_color_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bike_id BIGINT REFERENCES bikes(id) ON DELETE CASCADE,
    color_name TEXT,
    image_url TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE bikes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bike_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE bike_color_variants ENABLE ROW LEVEL SECURITY;

-- Policies (Example: Public Read, Admin Write)
-- CREATE POLICY "Public can view bikes" ON bikes FOR SELECT USING (true);
-- CREATE POLICY "Admins can manage bikes" ON bikes USING ( auth.role() = 'authenticated' ); -- Adjust based on your actual auth setup
